name: Build and publish
on:
  push:
    tags: '*'

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install frontend dependences
        run: bun install
        working-directory: ./frontend

      - name: build app
        run: $GOPATH/bin/wails build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/bin/elysium
          token: ${{ secrets.GITHUB_TOKEN }}




