name: Build and publish
on:
  push:
    tags: '*'

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install frontend dependences
        run: bun install
        working-directory: ./frontend

      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: elysium
          build-platform: linux/amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/bin/elysium
          token: ${{ secrets.GITHUB_TOKEN }}




